runtime: nodejs16

env_variables:
  REACT_APP_BACKEND_URL: 'https://liquid-terra-408616.as.r.appspot.com'
  REACT_APP_ENV: 'production'

handlers:
- url: /static
  static_dir: build/static

- url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|ttf|eot|map|txt|xml|yml))$
  static_files: build/\1
  upload: build/(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|ttf|eot|map|txt|xml|yml))$

- url: /.*
  static_files: build/index.html
  upload: build/index.html
